version: "3.1"

services:
  db:
    build:
      context: ./deploy/db
      dockerfile: ./Dockerfile
    restart: always
    environment:
      TZ: Asia/Kuala_Lumpur
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_admin
      POSTGRES_PASSWORD: todo_password
      PSQL_EDITOR: /usr/bin/nvim
    ports:
      - 5432:5432

  server:
    env_file:
      - path: ./dev.env
        required: true
    environment:
      SERVER_HOSTNAME: server
    build:
      context: .
      dockerfile: ./deploy/server/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
