version: "3.1"

services:
  db:
    build:
      context: ./deploy/db
      dockerfile: ./Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  server:
    build:
      context: .
      dockerfile: ./deploy/server/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
